apiVersion: apps/v1
kind: Deployment
metadata:
  name: nik-deployment
  labels:
    app: nik
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: nik
  template:
    metadata:
      labels:
        app: nik
    spec:
      containers:
        - name: nik
          image: {{IMAGE}}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nik-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: nik