apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-one
  labels:
    app: service-one
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: service-one
  template:
    metadata:
      labels:
        app: service-one
    spec:
      containers:
        - name: service-one
          image: {{IMAGE}}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-one
spec:
  selector:
    app: service-one
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30148
      protocol: TCP
      name: http