apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{DEPLOYMENT}}
  labels:
    app: {{DEPLOYMENT}}
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: {{DEPLOYMENT}}
  template:
    metadata:
      labels:
        app: {{DEPLOYMENT}}
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: {{DEPLOYMENT}}
          image: {{IMAGE}}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{DEPLOYMENT}}
spec:
  selector:
    app: {{DEPLOYMENT}}
  ports:
    - port: 8080
      protocol: TCP
      name: http