apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{DEPLOYMENT}}
  labels:
    app: {{DEPLOYMENT}}
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: {{DEPLOYMENT}}
  template:
    metadata:
      labels:
        app: {{DEPLOYMENT}}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: {{DEPLOYMENT}}
          image: {{IMAGE}}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{DEPLOYMENT}}
spec:
  selector:
    app: {{DEPLOYMENT}}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{DEPLOYMENT}}
spec:
  hosts:
    - "*"
  gateways:
    - nik-gwy
  http:
    - match:
        - uri:
            prefix: /{{DEPLOYMENT}}
      rewrite:
        uri: "/"
      route:
        - destination:
            host: {{DEPLOYMENT}}
            port:
              number: 80