apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-two
  labels:
    app: service-two
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: service-two
  template:
    metadata:
      labels:
        app: service-two
    spec:
      containers:
        - name: service-two
          image: {{IMAGE}}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-two
spec:
  selector:
    app: service-two
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30149
      protocol: TCP
      name: http